FROM node:18.16.1 as build

WORKDIR /usr/client

COPY . .

RUN npm i
RUN npm run build


FROM nginx

COPY ./nginx/nginx.config etc/nginx/nginx.config
COPY --from=build /usr/client/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
