apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: scrapper-db
  template:
    metadata:
      labels:
        service: scrapper-db
    spec:
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
      containers:
        - name: scrapper-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
