apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: scrapper-message-broker
  template:
    metadata:
      labels:
        service: scrapper-message-broker
    spec:
      volumes:
        - name: message-broker-storage
          persistentVolumeClaim:
            claimName: message-broker-persistent-volume-claim
      containers:
        - name: scrapper-message-broker
          image: rabbitmq:3.10.7-management
          ports:
            - containerPort: 15672
            - containerPort: 5672
          volumeMounts:
            - name: message-broker-storage
              mountPath: /var/lib/rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: mikhail21
            - name: RABBITMQ_DEFAULT_PASS
              value: gameoftanks21
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit disk_free_limit 2147483648
